url: //manateelazycat.github.io

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

plugins:
  - jekyll-feed
  
- name: Jekyll Deploy Action
  uses: jeffreytse/jekyll-deploy-action@v0.3.1
  